### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by higuitadiaz** [devCrossNet/vue-starter#313]
Hi guys!

May you can help me... I am having problems to deploy my first project with VUE-STARTER to heroku... in the deploy process display this error:

Do you have any idea what is the problem?
In addition and I using hte following extra dependence:
- Vuefire
- Firebase
- Vuetify

> "dependencies": {
    "accept-language": "3.0.18",
    "animejs": "2.2.0",
    "axios": "0.18.0",
    "body-parser": "1.18.3",
    "compression": "1.7.3",
    "config": "2.0.1",
    "cookie-parser": "1.4.3",
    "deepmerge": "2.2.1",
    "express": "4.16.4",
    "firebase": "^5.5.9",
    "js-cookie": "2.2.0",
    "lodash": "4.17.11",
    "lru-cache": "4.1.3",
    "marked": "0.5.1",
    "serve-favicon": "2.5.0",
    "vee-validate": "2.0.9",
    "vue": "^2.5.17",
    "vue-i18n": "8.2.1",
    "vue-meta": "1.5.5",
    "vue-router": "3.0.1",
    "vue-server-renderer": "2.5.17",
    "vuefire": "^1.4.5",
    "vuetify": "1.3.11",
    "vuex": "3.0.1",
    "vuex-router-sync": "5.0.0",
    "winston": "3.1.0"
  },

```
Building dependencies
       Installing node modules (package.json + package-lock)
       
       > grpc@1.16.0 install /tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc
       > node-pre-gyp install --fallback-to-build --library=static_library
       
       make: Entering directory '/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc/build'
         CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
       make: Entering directory '/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc/build'
         CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
         CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
       rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw': No such file or directory
       grpc.target.mk:470: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o' failed
       make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
       make: Leaving directory '/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc/build'
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
       gyp ERR! System Linux 4.4.0-1031-aws
       gyp ERR! command "/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/.heroku/node/bin/node" "/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc" "--napi_version=3" "--node_abi_napi=napi"
       gyp ERR! cwd /tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc
       gyp ERR! node -v v11.3.0
       gyp ERR! node-gyp -v v3.8.0
       gyp ERR! not ok 
       node-pre-gyp ERR! build error 
       node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/.heroku/node/bin/node /tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc/src/node/extension_binary/node-v67-linux-x64-glibc --napi_version=3 --node_abi_napi=napi' (1)
       node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
       node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
       node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
       node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
       node-pre-gyp ERR! System Linux 4.4.0-1031-aws
       node-pre-gyp ERR! command "/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/.heroku/node/bin/node" "/tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
       node-pre-gyp ERR! cwd /tmp/build_49d70e7cef3fbe2349f5b8d33dee0c3d/node_modules/grpc
       node-pre-gyp ERR! node -v v11.3.0
       node-pre-gyp ERR! node-pre-gyp -v v0.10.3
       node-pre-gyp ERR! not ok 
```

**Comment by farahbrunache** [comment]
Did you set the node version in your package.json? This might help, i.e.:

`  "engines": {
    "node": "8.11.1",
    "npm": "5.6.0"
  }`

And use whatever node version you want.

Also do you heroku build script in package.json? i.e.:

`"heroku-postbuild": "npm run build"`

**Comment by higuitadiaz** [comment]
Thank you @farahbrunache for your help!

yes, it's working now. I had to change the node version ">=8.0.0" to "8.16.0". I checked the version in heroku and I was running the version 11.

**Comment by devCrossNet** [comment]
@higuitadiaz is it ok if I close this issue?

**Comment by higuitadiaz** [comment]
@devCrossNet Yes please, the issue is completed! thanks o much!
