### ISSUE TITLE
Can't exit tests

### ISSUE THREAD

**Issue by tamer-mohamed** [devCrossNet/vue-starter#340]
**Describe the bug**

**To Reproduce**
1. Run tests `npm t`
2. try to exit the tests by `control + C`
3. Tests still running with error 

```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:628:16)
    at reportSuccess (/Users/mohamed_tamer/Desktop/frontend-app/node_modules/jest-worker/build/child.js:59:11)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:632:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Expected behavior**
Exit the test script.

**Comment by devCrossNet** [comment]
fixed in `"vue-starter-service": "1.0.0-beta.8"`
